project:
  type: website
  output-dir: _site

website:
  title: "Naruki Notsu"
  site-url: https://NarukiNotsu.github.io
  repo-url: https://github.com/NarukiNotsu/NarukiNotsu.github.io
  google-analytics: "G-YZSCCRTEQX"
  navbar: 
    left:
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
    tools: 
      - href: mailto:notsu.naru@gmail.com
        text: Send an email
        icon: envelope-plus
  page-footer:
    background: light
    center: |
      &#169; 2024 Naruki Notsu

format:
  html:
    theme: [cosmo,styles.scss]
    link-external-newwindow: true