---
title: "研究活動"
title-block-banner: true
editor: visual
---

## Published Paper

1. Naruki Notsu, Haruaki Hirota, Nobuo Akai (2025) "[Inter-municipal cooperation and tax enforcement capability](https://doi.org/10.1016/j.regsciurbeco.2025.104137) [*Regional Science and Urban Economics*](https://www.journals.elsevier.com/regional-science-and-urban-economics), Vol.114 104137-104137

2.  Notsu Naruki, Yosuke Abe, Shuko Harada (2025) "[The indirect effects of nuclear power plant accidents on population dynamics](https://www.tandfonline.com/doi/abs/10.1080/13504851.2025.2493771)," [*Applied Economics Letters*](https://www.tandfonline.com/journals/rael20),forthcoming

3.  Naruki Notsu (2024) "[Inter-municipal cooperation cloud and tax administrative costs](https://www.sciencedirect.com/science/article/pii/S0166046224000152)," [*Regional Science and Urban Economics*](https://www.journals.elsevier.com/regional-science-and-urban-economics), Vol.105, 103991-103991

4.  野津成希・広田啓朗 (2021) 「[自治体クラウドと市町村歳出－自治体クラウドと単独クラウドに着目した実証分析－](https://www.jstage.jst.go.jp/article/srs/51/2/51_235/_article/-char/ja/)」『[地域学研究](https://www.jstage.jst.go.jp/browse/srs/-char/ja)』, Vol.51, No.2, pp.235-253.

## Work in Progress & Working Papers

1.  Naruki Notsu, Shuko Harada, Shoya Abe (2025) "The consequences of fiscal decentralization: Decentralized police forces and local crime"

2.  Naruki Notsu, Asahi Semma, Shuko Harada (2025) "Complete Loss of Competition: Uncontested Elections and Political Rents"

3.  Naruki Notsu, Shuko Harada, Shoya Abe (2025) "Countering Incumbency Advantage: Challenger Strategy and Political Rents"

4.  Naruki Notsu, Yu Osaki, Shuko Harada (2025) "Evaluating the design of ICT implementation: financial impacts of standardized system specifications"

## 学会・セミナー報告など

1.  2025 年 9 月 25 日 Naruki Notsu, Shuko Harada, Shoya Abe 「Countering Incumbency Advantage: Challenger Strategy and Political Rents」(政経研究所 経済研究会, 日本大学) 

2.  2025 年 8 月 8 日 Naruki Notsu, Asahi Semma, Shuko Harada「Complete Loss of Competition: Uncontested Elections and Political Rents」(Japan Political Economy Group，Online)  

3.  2025 年 8 月 6 日 Naruki Notsu, Asahi Semma, Shuko Harada「Complete Loss of Competition: Uncontested Elections and Political Rents」(OSIPP Lunch Seminar, 大阪大学)  

4.  2025 年 3 月 26 日 Naruki Notsu, Shuko Harada, Shoya Abe「The consequences of partial fiscal decentralization: Decentralized police forces and local crime」(2025年度 実証財政・公共経済研究会, 松山大学) 

5.  2025 年 3 月 19 日 Naruki Notsu, Shuko Harada, Shoya Abe「The consequences of partial fiscal decentralization: Decentralized police forces and local crime」(東京大学財政ワークショップ, 東京大学) 

6.  2024 年 12 月 11 日 Naruki Notsu, Haruaki Hirota, Nobuo Akai「Inter-municipal cooperation and tax enforcement capability」(『公共事業に関わるマネジメントの課題と展望』研究会, 桃山学院大学)

7.  2024 年 12 月 7 日 Naruki Notsu, Haruaki Hirota, Nobuo Akai「Inter-municipal cooperation and tax enforcement capability」(1st Sino-Japanese SPACE Workshop Program, Osaka university)

8.  2024 年 11 月 15 日 Naruki Notsu, Haruaki Hirota, Nobuo Akai「Inter-municipal cooperation and tax enforcement capability」(National tax association 117th Annual Conference, Detroit Marriott at the Renaissance Center, Detroit, Michigan, U.S.A)

9.  2024 年 10 月 4 日 Naruki Notsu, Haruaki Hirota, Nobuo Akai「Inter-municipal cooperation and tax enforcement capability」(第 89 回「人材配置の経済学」研究会, Online)

10.  2024年7月30日 Naruki Notsu, Haruaki Hirota, Nobuo Akai「Inter-municipal cooperation and tax enforcement capability」(2024年度7月例会 神戸大学政治学研究会, 神戸大学)

11.  2024年5月26日 Naruki Notsu, Haruaki Hirota, Nobuo Akai「Inter-municipal cooperation and tax enforcement capability」(2024年度 第32回大会 日本地方財政学会, 慶應義塾大学)

12.  2024年3月27日 Naruki Notsu, Haruaki Hirota, Nobuo Akai「Inter-municipal cooperation and tax enforcement capability 」（2024年度 実証財政・公共経済研究会, 和歌山大学）

13. 2023年10月27日 Naruki Notsu「Inter-Municipal Cooperation cloud and tax administrative costs」(2023 Korean Association of Public Finance, Korea)

14. 2023年6月4日 Naruki Notsu「Do inter-municipal cooperation cloud systems affect tax administrative costs? Evidence from Japanese municipalities」(2023年度 第31回大会 日本地方財政学会, 名古屋市立大学)

15. 2023年5月27日 Naruki Notsu「Do inter-municipal cooperation cloud systems affect tax administrative costs? Evidence from Japanese municipalities」(2023年度 日本経済学会春季大会 ポスター報告, Online)

16. 2023年3月25日 Naruki Notsu「Do inter-municipal cooperation cloud systems affect tax administrative costs? Evidence from Japanese municipalities」(第7回 日本財政学会オンライン研究会, Online)

17. 2023年1月21日 Naruki Notsu「Do inter-municipal cooperation cloud systems affect tax administrative costs? Evidence from Japanese municipalities」(2022 年度 第1回 関西公共経済学研究会, 関西学院大学)

18. 2022 年 3 月 19 日 野津成希・広田啓朗「自治体クラウドと市町村歳出」(2021 年度第 5 回 関西公共経済学研究会)


## 受諾研究費

1. 2025 年 4 月 特別研究員奨励費

2. 2023 年 4 月 JST 次世代研究者挑戦的研究プログラム JPMJSP2138